// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Supabase's pooled connection (pgbouncer, port 6543) is what the app
  // uses at runtime via the driver adapter in lib/prisma.ts, but `prisma
  // migrate`/`generate` need a direct, non-pooled connection to run DDL —
  // hence DIRECT_URL, falling back to DATABASE_URL for non-Supabase setups
  // that only have one connection string.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
